# Generated by Django 2.2.5 on 2019-11-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('purchase', models.DecimalField(decimal_places=2, max_digits=5)),
                ('selling', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
